n1 = int(input('Escolha um numero? '))
n2 = int(input('escolha outro numero? '))
print('o resultado do numero {} e do numero {} em uma soma {}'.format(n1, n2,n1+n2), end='')
print(" em uma subtração {}".format(n1-n2), end='')
print(' em uma divisão {}'.format(n1/n2), end='')
print(' em uma divisão inteira {}'.format(n1//n2), end='')
print(' em uma muliplicação {}'.format(n1*n2), end='')
print(' em uma esponecição {}'.format(n1**n2), end='')
print(' sómente')